#pragma once

#define CAMERA_X_PX	640
#define CAMERA_Y_PX 480

#define STORE_ROW_BOUNDARY_COUNT	11
#define STORE_COL_BOUNDARY_COUNT	13

#define DEFAULT_STORE_ROW_START		77
#define DEFAULT_STORE_ROW_DISTANCE	39
#define DEFAULT_STORE_COL_START		55
#define DEFAULT_STORE_COL_DISTANCE	39

#define DEFAULT_ARM_STARTX			95
#define DEFAULT_ARM_STARTY			-144
#define DEFAULT_ARM_STARTZ			-101

#define DEFAULT_OFFSETX1			48
#define DEFAULT_OFFSETY1			74
#define DEFAULT_OFFSETX2			17
#define DEFAULT_OFFSETY2			294