#include "stdafx.h"
#include "Parameter.h"

#define STORE_ROW_BOUNDARY_COUNT	11
#define STORE_COL_BOUNDARY_COUNT	13
#define DEFAULT_STORE_ROW_START		0
#define DEFAULT_STORE_ROW_DISTANCE	50
#define DEFAULT_STORE_COL_START		0
#define DEFAULT_STORE_COL_DISTANCE	50

int StoreRowBoundary[STORE_ROW_BOUNDARY_COUNT] = {
	DEFAULT_STORE_ROW_START,
	DEFAULT_STORE_ROW_START + 1 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 2 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 3 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 4 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 5 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 6 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 7 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 8 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 9 * DEFAULT_STORE_ROW_DISTANCE,
	DEFAULT_STORE_ROW_START + 10 * DEFAULT_STORE_ROW_DISTANCE
};
int StoreColBoundary[STORE_COL_BOUNDARY_COUNT] = {
	DEFAULT_STORE_COL_START,
	DEFAULT_STORE_COL_START + 1 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 2 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 3 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 4 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 5 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 6 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 7 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 8 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 9 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 10 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 11 * DEFAULT_STORE_COL_DISTANCE,
	DEFAULT_STORE_COL_START + 12 * DEFAULT_STORE_COL_DISTANCE
};
int * CParameter::pStoreRowBoundary = StoreRowBoundary;
int * CParameter::pStoreColBoundary = StoreColBoundary;

CParameter::CParameter()
{
}


CParameter::~CParameter()
{
}
