//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TetrisPlace.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TETRISPLACE_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SERIAL               129
#define IDD_DIALOG_NEXTBLOCK            132
#define IDD_DIALOG_BOARD                134
#define IDD_DIALOG_ARMCONTROL           136
#define IDD_DIALOG_CAMERA               138
#define IDD_DIALOG_CONNECT              140
#define IDR_MENU_MAIN                   142
#define IDD_DIALOG_INFO                 143
#define IDD_DIALOG_STORESETTING         145
#define IDD_DIALOG_ARMSETTING           149
#define IDB_BITMAP_STOP                 155
#define IDD_DIALOG_HTTP                 156
#define IDD_LEFTCOL                     158
#define IDC_COMBO_SERIAL                1000
#define IDC_BUTTON_OPENPORT             1001
#define IDC_EDIT_RX                     1002
#define IDC_EDIT_TX                     1003
#define IDC_BUTTON_RUN                  1004
#define IDC_BUTTON_MODIFY               1005
#define IDC_BUTTON_SEND                 1006
#define IDC_BUTTON_REFRESH              1007
#define IDC_BUTTON_ADDTETRIS            1008
#define IDC_BUTTON_AUTONEXT             1009
#define IDC_BUTTON_PLACE                1010
#define IDC_STATIC_X                    1011
#define IDC_EDIT_X                      1012
#define IDC_GCOOR                       1013
#define IDC_STATIC_Y                    1014
#define IDC_EDIT_Y                      1015
#define IDC_STATIC_Z                    1017
#define IDC_EDIT_Z                      1018
#define IDC_BUTTON_COORGO               1019
#define IDC_GPUMP                       1020
#define IDC_BUTTON_OPENPUMP             1021
#define IDC_BUTTON_CLOSEPUMP            1022
#define IDC_GSTEER                      1023
#define IDC_BUTTON_STEERGO              1024
#define IDC_EDIT_STEER                  1025
#define IDC_STATIC_X2                   1026
#define IDC_STATIC_AX                   1027
#define IDC_GANGLE                      1028
#define IDC_EDIT_ANGLEX                 1029
#define IDC_STATIC_Y2                   1030
#define IDC_STATIC_AY                   1031
#define IDC_EDIT_ANGLEY                 1032
#define IDC_STATIC_X4                   1033
#define IDC_STATIC_AZ                   1034
#define IDC_EDIT_ANGLEZ                 1035
#define IDC_BUTTON_GOANGLE              1036
#define IDC_BUTTON_UNLOCK               1037
#define IDC_RELATIVE                    1038
#define IDC_ABSOLUTE                    1039
#define IDC_GAR                         1040
#define IDC_GMODE                       1041
#define IDC_SETTINGON                   1042
#define IDC_SETTINGOFF                  1043
#define IDC_BUTTON_GRAB                 1044
#define IDC_GSTATE                      1045
#define IDC_STATE                       1046
#define IDC_GMOVE                       1047
#define IDC_STATIC_MOVEX                1048
#define IDC_EDIT_MOVEX                  1049
#define IDC_STATIC_MOVEY                1050
#define IDC_EDIT_MOVEY                  1051
#define IDC_STATIC_ToX                  1052
#define IDC_EDIT_MOVEX2                 1053
#define IDC_BUTTON_LOCK                 1053
#define IDC_EDIT_MOVEToX                1054
#define IDC_STATIC_ToY                  1055
#define IDC_EDIT_MOVEY2                 1056
#define IDC_EDIT_MOVEToY                1057
#define IDC_BUTTON_MOVE                 1058
#define IDC_STATIC_R                    1059
#define IDC_EDIT_MOVER                  1060
#define IDC_PICTURE                     1061
#define IDC_BUTTON_SEGGO                1062
#define IDC_COMBO_PORT                  1063
#define IDC_STATIC_PORT                 1064
#define IDC_BUTTON_SETZERO              1065
#define IDC_COMBO_CAMERA                1066
#define IDC_TAB_SERIAL                  1067
#define IDC_STATIC_CAMERA               1068
#define IDC_RADIO_LOOP                  1069
#define IDC_RADIO_ONCE                  1070
#define IDC_COMBO_TETRIS                1071
#define IDC_BUTTON_CON                  1072
#define IDC_BUTTON_REFRESHBOARD         1073
#define IDC_BUTTON_ARMCORRECT           1074
#define IDC_EDIT_NEXT                   1075
#define IDC_BUTTON_XGO                  1077
#define IDC_BUTTON_YGO                  1078
#define IDC_BUTTON_ZGO                  1079
#define IDC_LIST_RANK                   1080
#define IDC_RADIO_STORE1                1081
#define IDC_RADIO_STORE2                1082
#define IDC_STATIC_GSTORE               1083
#define IDC_STORE_ROWDIS                1084
#define IDC_STORE_COLDIS                1085
#define IDC_STORE_X                     1086
#define IDC_STORE_Y                     1087
#define IDC_STORE_X0                    1089
#define IDC_STORE_X1                    1090
#define IDC_STORE_X2                    1091
#define IDC_STORE_X3                    1092
#define IDC_STORE_X4                    1093
#define IDC_STORE_X5                    1094
#define IDC_STORE_X6                    1095
#define IDC_STORE_X7                    1096
#define IDC_STORE_X8                    1097
#define IDC_STORE_X9                    1098
#define IDC_STORE_X10                   1099
#define IDC_STORE_X11                   1100
#define IDC_STORE_X12                   1101
#define IDC_STORE_Y0                    1102
#define IDC_STORE_Y1                    1103
#define IDC_STORE_Y2                    1104
#define IDC_STORE_Y3                    1105
#define IDC_STORE_Y4                    1106
#define IDC_STORE_Y5                    1107
#define IDC_STORE_Y6                    1108
#define IDC_STORE_Y7                    1109
#define IDC_STORE_Y8                    1110
#define IDC_STORE_Y9                    1111
#define IDC_STORE_OK                    1112
#define IDC_STORE_CANCEL                1113
#define IDC_STORE_Y10                   1114
#define IDC_STORE_DEFAULT               1115
#define IDC_ARM_STARTX                  1117
#define IDC_ARM_STARTY                  1118
#define IDC_ARM_STARTZ                  1119
#define IDC_EMERGENCY                   1120
#define IDC_OPENHTTP                    1121
#define IDC_TAB                         1122
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_MENU_STORESET                32778
#define ID_MENU_ARMSET                  32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
